# Week 1 tutorial: Linear regression

### Introduction
In this exercise, you will implement linear regression and get to see it work on data. Hopefully you have watched the video lectures associated with this week. **Please keep the function declarations as they are.**

To get started with this exercise, you will need to download the Week 1 folder from the github or dropbox.

### External files included for this exercise
 - $\texttt{ex1data1.txt}$ - Dataset for linear regression with one variable
 - $\texttt{ex1data2.txt}$ - Dataset for linear regression with multiple variables


In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

## 1- Simple numpy function

Let's kick things off by making a happy little identity matrix. 

**Exercise:** Make a function that takes nothing in, and returns a 5x5 identity matrix.

*Hint: check the documentation for `np.eye()` and `np.identity()`.*


In [ ]:
def warmUp():
    ### START CODE HERE ###

    ### END CODE HERE ###
    return A
print('Diagonal matrix of ones:\n', warmUp())

**Expected Output:**

`Diagonal matrix of ones:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]`


## 2 - Linear regression with one variable
In this section you will implement linear regression with a single varaible to predict profits. We have ascertained data from food trucks in various cities that breaks down the profits and populations of those cities. A particularly daft business executive from *Mangia con Maffetone LLC* has approached you with this data and asked for advice on which city to expand to next.

The file $\texttt{ex1data1.txt}$ contains the dataset for our linear regression prob- lem. The first column is the population of a city and the second column is the profit of a food truck in that city. A negative value for profit indicates a loss. The file is loaded using the commands in the cell below. 

In [ ]:
data = np.loadtxt('./data/ex1data1.txt',delimiter=',') #Loads simple comma separated values
X = data[:,0] # Sets all (:) of the first (0) column equal to a new variable X
y = data[:,1] # Sets the second column to y
m = y.shape[0]
print("Number of training examples =",m)

### 2.1 Plotting the data
Before starting on any task, it is often useful to understand the data by visualizing it. For this dataset, you can use a scatter plot to visualize the data, since it has only two properties to plot (profit and population). (Many other problems that you will encounter in data science are multi-dimensional and can’t be plotted on a 2D plot.)

**Exercise:** Using the X, y variables from above create a plot of the 2D data. Label the y-axis as "Profit in 10,000s" and the x-axis "Population of City in 10,000s". Use red x's for the markers.<br>
*Hint: matplotlib.pyplot has been imported as plt*

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

**Expected Output:**
<img src="data/plot.png" style="width: 400px">

### 2.2 - Gradient Descent
In this part, you will fit the linear regression parameters θ to our dataset using gradient descent.

#### 2.2.1 - Update Equations
The objective of linear regression is to minimize the cost (loss) function
\begin{equation*}
J(\theta) = \frac{1}{2m}\sum^{m}_{i=1} (h_\theta(x^{(i)})-y^{(i)})^2
\end{equation*}
where the hypothesis $h_\theta(x)$ is given by the linear model
\begin{equation*}
h_\theta(x) = \theta^Tx = \theta_0 + \theta_1x_1.
\end{equation*}

Recall that the parameters of your model are the $\theta_j$ values. These are the values you will adjust to minimize cost $J(\theta)$. One way to do this is to use the batch gradient descent algorithm. In batch gradient descent, each iteration performs the update
\begin{equation*}
\theta_j := \theta_j - \alpha\frac{1}{m}\sum^{m}_{i=1} (h_\theta(x^{(i)})-y^{(i)})x_j^{(i)}
\end{equation*}
simultaneously for all $j$. 
With each step of gradient descent, your parameters $\theta_j$ come closer to the optimal values that will achieve the lowest cost $J(\theta)$.

#### 2.2.2 - Implementation
- Below the data is already set up for linear regression. We add another dimesion (of ones) to our data to accomodate the $\theta_0$ intercept term. 
- We also initialize the parameters to 0 and the learning rate `alpha` to 0.01.
- Finally, because of array broadcasting rules, life will be easier to debug if we enforce linear algebra. Thus when you make vectors (nx1 arrays), force them into a (n,1) shape instead of the numpy default of (n,). 

In [ ]:
X = np.zeros((m,2)) #Start with a matrix of zeros with 2 columns of m training examples in each row
X[:,0] = np.ones(m) # Set the first column to all 1, to multiply against constant parameter
X[:,1] = data[:,0] # X data for the first order linear parameter
y=y[:,np.newaxis] # This makes y have the shape (97,1) instead of (97,). This is an important implementation distinction. 
theta = np.zeros((2,1)) # Initialize fitting parameters (weights)

iterations = 1500
alpha = 0.01 # learning rate

#### 2.2.3 - Computing the cost $J(\theta)$
As you perform gradient descent to learn minimize the cost function $J(\theta)$, it is helpful to monitor the convergence by computing the cost. In this section, you will implement a function to calculate  $J(\theta)$ so you can check the convergence of your gradient descent implementation.

**Exercise:** Complete the function `compute_cost()`, which is a function that computes --- you guessed it --- $J(\theta)$. <br>
*Hint: As you are doing this, remember that $X$ and $y$ are not scalar values, but matricies whose rows represent the examples from the training set. Consider using `np.matmul()` or `np.dot()`.*

In [ ]:
def compute_cost(X,y,theta):
    '''
    Computes the cost for linear regression
    J = compute_cost(X,y,theta) computes the cost of using theta as the
    parameter for linear regression to fit the data points in X and y.
    '''
    
    m = y.shape[0] #Number of training examples
    J = 0;
    ### START CODE HERE ###

    ### END CODE HERE ###
    return J
print("{:5.2f}".format(compute_cost(X,y,theta)))

**Expected Output:**<br>
32.07

#### 2.2.4 - Gradient Descent
Next you will implement the gradient descent algorithm. The loop structure has been written for you, and you only need to supply the updates to $\theta$ within each iteration. 

As you program, make sure you understand what you are trying to optimize and what is being updated. Keep in mind that the cost $J(\theta)$ is parameterized by the vector $\theta$, and not $X$ and $y$. That is, we minimize the value of $J(\theta$) by changing the values of the vector $\theta$, and not by changing $X$ or $y$. 

**Exercise:** Complete the loop in the function `gradient_descent()` to provide the update for $\theta$. Please refer to the equations from the video lectures, or above.<br>
*Hint: Make sure to vectorize your code using matrix multiplications. If you are unsure of operations, it may help to consider the shape of given arrays and the necessary resultand shapes.*

In [ ]:
def gradient_descent(X,y,theta,alpha,num_iters):
    '''
    Performs gradient descent to learn theta
    
    Inputs
    ===============
    X: input features
    y: desired ouput values
    alpha: learning rrate
    num_iters: number of iteratons for learning
    
    Returns
    ===============
    theta: final learned weights
    J_history: list of loss over each itteration
    '''
    m = y.shape[0] #Number of training examples
    J_history = np.zeros((num_iters,1))
    
    for i in range(num_iters):
        ### START CODE HERE ###

        ### END CODE HERE ###
        J_history[i] = compute_cost(X,y,theta)
    return theta, J_history
    

Below we run the gradient descent function and plot the resultant linear regression fit, as well as the returned loss history. This history allows us to ensure that the loss function is indeed decreasing over time. 

In [ ]:
# Example run
learned_theta, J_hist = gradient_descent(X,y,theta,alpha,iterations)
# Example plotting
fig=plt.figure(figsize=(12,6))
ax1 = fig.add_subplot(1,2,1)
ax1.plot(X[:,1],y,'rx',MarkerSize=5)
plt.xlabel("Population of City in 10,000s")
plt.ylabel("Profit in $10,000s")
ax1.plot(X[:,1],np.dot(X,learned_theta),'b-')
ax2 = fig.add_subplot(1,2,2)
ax2.plot([a for a in range(iterations)], J_hist,'k.',MarkerSize=5)
plt.xlabel("Number of iterations")
plt.ylabel("Loss")
plt.show()
print('Learned value of theta0:{:7.3f}'.format(learned_theta[0,0]),
      '\nLearned value of theta1:{:7.3f}'.format(learned_theta[1,0]))
# Make a prediction
predict1 = np.dot(np.array([1,3.5]),learned_theta)
print(predict1)
print('For population = 35,000, we predict a profit of ${:8.2f}'.format(predict1[0]*10000))

**Expected Output:**
<img src="data/plot2.png" style="width: 600px"><br>
Learned value of theta0: -3.630 <br>
Learned value of theta1:  1.166<br>
For population = 35,000, we predict a profit of $ 4519.77


### 2.4 - Visualizing $J(\theta)$

To get an understanding of the the cost function, let's plot the cost over a 2-d grid of $\theta_0$ and $\theta_1$ values. You will not need to code anything new for this part, but you should understand how the code you have written already is creating these images. 

The important thing to observe is that the loss function is a convex function that has a clear global minimum that we can find with ease. 

In [ ]:
# Initialize grid
theta0_vals = np.linspace(-10, 10,100);
theta1_vals = np.linspace(-1, 4,100);
t0,t1 = np.meshgrid(theta0_vals,theta1_vals)
J_vals = np.zeros((t0.shape))

#Fill out values
for i in range(t0.shape[0]):
    for j in range(t0.shape[1]):
        t = np.array([t0[i,j],t1[i,j]]).reshape(2,1)
        J_vals[i,j] = compute_cost(X,y,t)

In [ ]:
from mpl_toolkits.mplot3d import axes3d, Axes3D 
from matplotlib import cm
fig=plt.figure(figsize=(12,6))
ax1 = fig.add_subplot(1,2,1)
ax1.contour(theta0_vals,theta1_vals,np.log(J_vals),15,
           cmap=cm.coolwarm)
ax1.plot(learned_theta[0,0],learned_theta[1,0],'rx')
plt.xlabel(r'$\theta_0$')
plt.ylabel(r'$\theta_1$')
ax2 = fig.add_subplot(1,2,2,projection='3d')

ax2.plot_surface(t0,t1,J_vals,cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)
plt.xlabel(r'$\theta_0$')
plt.ylabel(r'$\theta_1$')
plt.show()

## 3 - Linear regression with multiple variables
TBC

# Tests
The cell below will test the functions you produced above, marking failed/ok tests. 

In [ ]:
import unittest

class TestWeek1(unittest.TestCase):
    def setUp(self):
        self.id = np.eye(5)
        self.theta = np.zeros((2,1))
        data = np.loadtxt('./data/ex1data1.txt',delimiter=',')
        m=data.shape[0]
        self.X = np.ones((m,2))
        self.X[:,1] = data[:,0] 
        self.y = data[:,1]
        self.y = y.reshape((m,1))
    def test_identity(self):
        self.assertTrue((warmUp().shape[0] == warmUp().shape[1]) and np.allclose(warmUp(), self.id))

    def test_compute_cost(self):
        self.assertTrue(np.abs((compute_cost(self.X,self.y,self.theta))-32.072)<0.001)
        
    def test_gradient_descent(self):
        lt ,_= gradient_descent(X,y,theta,0.02,2000)
        self.assertTrue(np.abs(lt[0,0]--3.8928)<0.0001 and np.abs(lt[1,0]-1.1927)<0.0001)
unittest.main(argv=[''], verbosity=2, exit=False)